python run.py \
  --do_train \
  --do_predict \
  --evaluation_strategy epoch \
  --num_train_epochs 1 \
  --max_train_samples 500 \
  --max_eval_samples 500 \
  --max_predict_samples 500 \
  --learning_rate 2e-5 \
  --dataset_name ./Datasets/THUCNews/THUCNewsOneHot.py \
  --model_name_or_path ../model_file/bert-base-chinese \
  --output_dir ./Output/THUCNews \
  --cache_dir ./Cache \
  --max_seq_length 128 \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 8 \
  --save_strategy epoch \
  --overwrite_output_dir