python run.py \
  --do_train \
  --do_predict \
  --evaluation_strategy epoch \
  --learning_rate 2e-5 \
  --max_train_samples 500 \
  --max_eval_samples 500 \
  --max_predict_samples 500 \
  --dataset_name ../Datasets/ClueNER/ClueNER.py \
  --model_name_or_path ../../model_file/bert-base-chinese \
  --output_dir ./Output/ClueNER/ \
  --cache_dir ./Cache \
  --num_train_epochs 5 \
  --max_seq_length 256 \
  --per_device_train_batch_size 32 \
  --per_device_eval_batch_size 32 \
  --overwrite_output_dir
